Mounting collection instructions
statamic/v2-docs pull request #388
Opened 2018-11-30 14:11 UTC by admench

Add instructions on how to actually mount a collection.

2018-11-30 14:22 UTC, jasonvarga requested changes

2018-11-30 14:22 UTC, jasonvarga commented on content/collections/docs/collections.md
> +It's really easy to mount a collection to a page, simply click the 3 dots to the right of the page name, when in the index view of pages, and mount a selected collection. Or if you want to add it to
Good idea, although you're telling people to edit `collections/collection-name/index.md` - but you should be editing a page. Maybe change it to

> add it to the appropriate `index.md` inside `site/content/pages`

2018-12-02 20:24 UTC, admench commented on content/collections/docs/collections.md
> +It's really easy to mount a collection to a page, simply click the 3 dots to the right of the page name, when in the index view of pages, and mount a selected collection. Or if you want to add it to
I agree. I've made a change to the example!

2018-12-03 22:20 UTC, merged

2018-12-04 07:25 UTC, admench commented
Wooo